apiVersion: v1
kind: Service
metadata:
  labels:
    run: ping-server
  name: ping-server
  namespace: scenario-3
spec:
  ports:
  - name: "pingport"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: ping-server
  sessionAffinity: None

