apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pong-server
  name: pong-server
  namespace: scenario-3
spec:
  ports:
  - name: "pongport"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: pong-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
